# Generated by Django 4.1.1 on 2022-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='groups', to='users.usedmodel')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
