# Generated by Django 4.1.1 on 2022-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
